### ISSUE TITLE
embedding层的梯度问题

### ISSUE THREAD

**Issue by xingt-tang** [bytedance/LargeBatchCTR#1]
为什么embedding layer返回的梯度是dense的，对每个idx都有一个梯度？
另外，embedding layer返回indexslice时候，gather对应的权重，axis应该为0？

**Comment by zhengzangw** [comment]
我们的实现中使用了 L2-norm 作用在所有的 embedding 上，所以每个 idx 都有梯度

**Comment by xingt-tang** [comment]
get it!
